# Generated by Django 4.2.4 on 2023-08-31 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
