# Generated by Django 4.2.4 on 2023-08-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0002_alter_swiftuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiftuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='swiftuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
