# Generated by Django 4.2.4 on 2023-09-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsflow', '0002_ridestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.JSONField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='current_status',
            field=models.CharField(choices=[('Arrived', 'Arrived'), ('En Route', 'En Route'), ('Waiting for Pickup', 'Waiting for Pickup'), ('In Progress - En Route', 'In Progress - En Route'), ('In Progress - On Pickup', 'In Progress - On Pickup'), ('Cancelled', 'Cancelled'), ('Booked', 'Booked'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Driver Assigned', 'Driver Assigned'), ('Payment Pending', 'Payment Pending'), ('Review Pending', 'Review Pending'), ('Expired', 'Expired'), ('Rescheduled', 'Rescheduled'), ('No Show', 'No Show')], default='Booked', max_length=30),
        ),
        migrations.DeleteModel(
            name='RideState',
        ),
        migrations.AddField(
            model_name='currentlocation',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wsflow.ride'),
        ),
    ]
