# Generated by Django 4.2.4 on 2023-09-07 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_company', models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('BMW', 'BMW')], max_length=100)),
                ('vehicle_model', models.CharField(blank=True, choices=[('Camry', 'Camry'), ('Corolla', 'Corolla'), ('Prius', 'Prius'), ('Mustang', 'Mustang'), ('F-150', 'F-150'), ('Explorer', 'Explorer'), ('Golf', 'Golf'), ('Passat', 'Passat'), ('Jetta', 'Jetta'), ('Civic', 'Civic'), ('Accord', 'Accord'), ('CR-V', 'CR-V'), ('Silverado', 'Silverado'), ('Equinox', 'Equinox'), ('Malibu', 'Malibu'), ('Altima', 'Altima'), ('Maxima', 'Maxima'), ('Rogue', 'Rogue'), ('3 Series', '3 Series'), ('5 Series', '5 Series'), ('X5', 'X5')], max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('vehicle_pic', models.ImageField(upload_to='media/vehicle_pics/')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
