# Generated by Django 4.2.4 on 2023-09-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta')], default='Unknown', max_length=20),
        ),
    ]
